// ==========================================
// vite.config.js
// ==========================================
// Vite build tool configuration for the
// GasGuard Vue 3 frontend.
//
// Vite handles:
//   - Dev server with hot module replacement
//   - Vue single file component compilation
//   - Path aliases for clean imports
//   - Production build optimization
//   - Environment variable loading (.env)
// ==========================================

import { defineConfig } from "vite";
import vue              from "@vitejs/plugin-vue";
import { fileURLToPath, URL } from "node:url";

export default defineConfig({
  // ==========================================
  // Plugins
  // ==========================================
  // @vitejs/plugin-vue enables .vue single
  // file component support (template, script,
  // style in one file)
  // ==========================================
  plugins: [
    vue(),
  ],

  // ==========================================
  // Path Aliases
  // ==========================================
  // Allows clean imports using @ instead of
  // long relative paths like ../../components
  //
  // Example:
  //   import BaseCard from "@/components/common/BaseCard.vue"
  //   instead of:
  //   import BaseCard from "../../components/common/BaseCard.vue"
  // ==========================================
  resolve: {
    alias: {
      "@": fileURLToPath(new URL("./src", import.meta.url)),
    },
  },

  // ==========================================
  // Dev Server Configuration
  // ==========================================
  server: {
    port: 5173,          // Default Vite port — matches CORS in backend server.js
    open: true,          // Auto-open browser on npm run dev
    strictPort: true,    // Fail if port 5173 is already in use

    // Proxy API requests to the backend
    // during development so the Vue app
    // at localhost:5173 can call the Node.js
    // backend at localhost:3000 without CORS issues.
    //
    // Example:
    //   fetch("/api/status") in Vue
    //   → proxied to http://localhost:3000/api/status
    proxy: {
      "/api": {
        target:      "http://localhost:3000",
        changeOrigin: true,
        secure:       false,
      },
    },
  },

  // ==========================================
  // Build Configuration
  // ==========================================
  // Settings for the production build
  // output generated by npm run build
  // ==========================================
  build: {
    outDir:          "dist",      // Output folder
    sourcemap:       false,       // Disable sourcemaps in production
    chunkSizeWarningLimit: 1000,  // Suppress warnings for larger chunks

    rollupOptions: {
      output: {
        // Split vendor libraries into a separate
        // chunk for better browser caching —
        // app code changes often, vendor code rarely
        manualChunks: {
          vendor:   ["vue", "vue-router", "pinia"],
          firebase: ["firebase/app", "firebase/auth", "firebase/firestore"],
          charts:   ["chart.js", "vue-chartjs"],
        },
      },
    },
  },

  // ==========================================
  // Environment Variables
  // ==========================================
  // Vite exposes env vars prefixed with VITE_
  // to the frontend code via import.meta.env
  //
  // Example in .env:
  //   VITE_FIREBASE_API_KEY=your-key-here
  //
  // Usage in code:
  //   const key = import.meta.env.VITE_FIREBASE_API_KEY
  //
  // Variables WITHOUT the VITE_ prefix are
  // server-only and never exposed to the browser
  // ==========================================
  envPrefix: "VITE_",
});